apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion-service
  labels:
    app: currency-conversion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - name: currency-conversion
        image: currency-conversion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8100
        env:
        - name: currency-conversion-config
          valueFrom:
            configMapKeyRef:
              name: currency-exe-configmap
              key: currency-exc-url
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
spec:
  selector:
    app: currency-conversion
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: 30000